name: work-1
on:
  push:
    branches:
      - main
jobs:
  hello1:
    runs-on: self-hosted
    steps:
      - name: sayHi
        run: echo "Hi"
      - name: sayMyName
        run: echo "${{ github.actor }}"
